### ISSUE TITLE
No module named 'rational'

### ISSUE THREAD

**Issue by hitzhangyu** [Adamdad/rational_kat_cu#1]
File "/KAT/rational_kat_cu/tests/test.py", line 3, in <module>
    from rational.torch import Rational
ModuleNotFoundError: No module named 'rational'

**Comment by Adamdad** [comment]
Dear @hitzhangyu , Could you please install the Rational Activations library from https://github.com/ml-research/rational_activations? This library provides learnable activation functions using rational functions. We use it as `ground-truth` to test our implementation.

**Comment by hitzhangyu** [comment]
Thanks！
